version: 2

project_name: gofaux

release:
  github:
    owner: tjb
    name: gofaux

builds:
  - id: gofaux
    main: ./cmd/gofaux
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
    binary: gofaux

archives:
  - id: gofaux_archives
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

brews:
  - name: gofaux
    description: "versatile cli tool that captures and stores json requests, allowing you to replay them as needed."
    homepage: "https://github.com/tjb/gofaux"
    install: |
      bin.install "gofaux"
    test: |
      system "#{bin}/gofaux --help"
    commit_author:
      name: "GitHub Actions" 
      email: "actions@github.com"
    dependencies: []
    skip_upload: false
    url_template: "https://github.com/tjb/gofaux/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: tjb
      name: homebrew-gofaux
